### ISSUE TITLE
Kay's comments

### ISSUE THREAD

**Issue by kaychan1989** [Chhr1s/GA_DOE_Public#3]
I had an issue with the package tidyverse, similar to what I had with Joe’s codes. I was trying to remove and reinstall the package, but it was not successful. I still got an error regarding tibble, and I could not run Chris’ codes. So, I filed an issue instead. Please see below for my comments:

**Areas of strengths:**
Overall you did a very fantastic job, Chris! I was very impressed by the way that you organize your data before creating visuals. I think you have used almost all of the functions we learned this term (e.g., join, gt, flexdashboard). I also like you created Chart B to provide additional detail regarding the plot on the General page.

**Areas of improvements:**
One general area that you may consider is to provide additional texts explaining the visuals. Without looking at the codes, it was a bit challenging to understand each visual’s meaning. Please see below for more detailed comments.

Regarding the plot in the General tab,

-   It’s a bit unclear, especially for someone who did not see the codes to get the sense of individual districts on the y-axis. I think there are quite too many geom_cols that could make it’s difficult for interpretation and increase the cognitive burden for people who want to track down punishment for each district. I am not sure, though, If you would like to emphasize individual districts. You may ignore this comment if it’s not the case. You may also select to highlight some districts with high rates of harsh punishment using gghighlight.
-   Regarding the color of a proportion of Black students per district, the scale_fill_distiller(palette =
  ‘Blues’) gave the color shade that is quite similar to the shade of geom_col of individual districts. It was difficult to visually separate or tell the meaning of the geom_col color and the scale_fill color, which both are similarly bluish.
-  Legend also overlays the caption, but I am sure you will fix this for the final product.

Regarding the School Admin plot,
-   Some of the panel.labels are beyond the visual borders.
-   Non-academic viewers or those who are not familiar with the dataset might not understand the abbreviations (e.g., Prop., Prop. FRL).
- 
**Things that I learned:**
-   As the visuals were created from minor datasets, I got to review joining and data-wrangling. Chris also did a few regression analyses. I was thinking at first when I see those codes that he might use stargazer, which is my favorite package! However, getting to learn about gt is very cool too, especially after the class lecture about how to create tables.

Finally, I think you rock and are on the way to be a data scientist! Keep going!

@datalorax

**Comment by datalorax** [comment]
Really nice and detailed review, Kay! Particularly given that you were having trouble with your package installs.
